project:
  type: website

website:
  title: "G2-3"
  navbar:
    left:
      - href: overview.qmd
        text: Overview
      - href: methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis
      - href: findings.qmd
        text: Results & Discussion
      - href: lessonlearnt.qmd
        text: Lessons Learnt
    right:
      - href: overview.qmd
        text: Overview
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

