# Lesson Learnt

From our above analysis, we have learnt that the merger of 4 Junior Colleges did not really have a huge impact on accessibility. This is because the Singapore transport system is so well developed that both the bus network and MRT stations cover almost every part of Singapore. This statement is clearly not over exaggerated given the example that Singapore has just newly opened the Thomson-East Coast line Stage 3 recently. This newly opened line aims to connect the North-West of Singapore to the South of Singapore, making it much easier for commuters to reach other regions of Singapore without having to transfer between MRT lines.\

With that in mind, our group has concluded that the closure of schools is a right step taken by the government as such to better divert resources to improve the quality of education while not compromising the accessibility of schools. Also, we have also identified that there are other varying reasons why schools that are selected to close/merge. We should have the fullest confidence in the Government and trust their decision in closing certain schools. Most importantly, we should see things on a broader scale, by closing schools, resources could be diverted for better purposes, benefiting the students in Singapore\'s Education System, ultimately, making better contributions to the society.

\

